config/routes.rb
Rails.application.routes.draw do
  resources :clothings do
      collection { post :upload }
    end
  resources :outfits

end

app/models/article.rb
class Article
  include Mongoid::Document
  field :name, type: String
  field :content, type: String
  field :published_on, type: Date
  has_and_belongs_to_many :authors, autosave: true
end

app/models/author.rb
class Author
  include Mongoid::Document
  field :name, type: String
  field :_id, type: String, default: ->{ name }
  has_many :articles, autosave: true
end

app/models/clothing.rb
class Clothing
  include Mongoid::Document
  field :description, type: String
  field :category, type: String
  field :brand, type: String
  field :color, type: String
  field :datafile, type: String
  field :_id, type: String, default: ->{ description }
  has_many :outfits, autosave: true
end

app/models/outfit.rb
class Outfit
  include Mongoid::Document
  field :event, type: String
  field :notes, type: String
  field :worn_on, type: Date
  has_and_belongs_to_many :clothings, autosave: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clothings_controller.rb
# encoding: utf-8
class ClothingsController < ApplicationController
  before_action :set_clothing, only: [:show, :edit, :update, :destroy]

  # GET /clothings
  # GET /clothings.json
  def index
    @clothings = Clothing.all
  end

  # GET /clothings/1
  # GET /clothings/1.json
  def show
  end

  # GET /clothings/new
  def new
    @clothing = Clothing.new
  end

  # GET /clothings/1/edit
  def edit
  end

  # POST /clothings
  # POST /clothings.json
  def create
    @clothing = Clothing.new(clothing_params)
    Image.save_file(clothing_params[:datafile])


    respond_to do |format|
      if @clothing.save
        format.html { redirect_to @clothing, notice: 'Clothing was successfully created.' }
        format.json { render :show, status: :created, location: @clothing }
      else
        format.html { render :new }
        format.json { render json: @clothing.errors, status: :unprocessable_entity }
      end
    end


  end



  # PATCH/PUT /clothings/1
  # PATCH/PUT /clothings/1.json
  def update
    respond_to do |format|
      if @clothing.update(clothing_params)

        format.html { redirect_to @clothing, notice: 'Clothing was successfully updated.' }
        format.json { render :show, status: :ok, location: @clothing }
      else
        format.html { render :edit }
        format.json { render json: @clothing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clothings/1
  # DELETE /clothings/1.json
  def destroy
    @clothing.destroy
    respond_to do |format|
      format.html { redirect_to clothings_url, notice: 'Clothing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clothing
      @clothing = Clothing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clothing_params
      params.require(:clothing).permit(:description, :category, :brand, :color, :datafile)
    end
end

app/controllers/images_controller.rb
# class ImagesController < ApplicationController
#   def index
#     @clothing = Clothing.find(params[:id])
#     @images = @clothing.images
#   end

#   def upload
#     DataFile.save_file(params[:upload])
#     redirect_to images_path(:clothings_id => params[:clothing_id])
#   end
# end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
  before_action :set_outfit, only: [:show, :edit, :update, :destroy]

  # GET /outfits
  # GET /outfits.json
  def index
    @outfits = Outfit.all
  end

  # GET /outfits/1
  # GET /outfits/1.json
  def show
  end

  # GET /outfits/new
  def new
    @outfit = Outfit.new

  end

  # GET /outfits/1/edit
  def edit
  end

  # POST /outfits
  # POST /outfits.json
  def create
    # @outfit[:clothing_ids] = params[:outfit][:clothing_ids].split(',')
    @outfit = Outfit.new(outfit_params)

    respond_to do |format|
      if @outfit.save
        format.html { redirect_to @outfit, notice: 'outfit was successfully created.' }
        format.json { render :show, status: :created, location: @outfit }
      else
        format.html { render :new }
        format.json { render json: @outfit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outfits/1
  # PATCH/PUT /outfits/1.json
  def update
    respond_to do |format|
      if @outfit.update(outfit_params)
        format.html { redirect_to @outfit, notice: 'outfit was successfully updated.' }
        format.json { render :show, status: :ok, location: @outfit }
      else
        format.html { render :edit }
        format.json { render json: @outfit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outfits/1
  # DELETE /outfits/1.json
  def destroy
    @outfit.destroy
    respond_to do |format|
      format.html { redirect_to outfits_url, notice: 'outfit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_outfit
      @outfit = Outfit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def outfit_params
      params.require(:outfit).permit(:event, :notes, :worn_on, clothing_ids: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clothings_helper.rb
module ClothingsHelper
end

app/helpers/outfits_helper.rb
module OutfitsHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :published_on %><br>
    <%= f.date_select :published_on %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>

  <div class="field">
  <%= f.label :author_ids %><br />
  <%= f.select :author_ids, Author.all.collect {|a| [a.name, a.id] }, {}, :multiple => true %>
  </div>

  <div class="field">
  <%= f.label :author_ids_2 %><br />
  <%= f.select :author_ids, Author.all.collect {|a| [a.name, a.id]  }, {}, :multiple => true %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clothings/_form.html.erb
<%= form_for(@clothing) do |f| %>
  <% if @clothing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clothing.errors.count, "error") %> prohibited this Clothing from being saved:</h2>

      <ul>
      <% @clothing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

   <div class="field">
  <%= f.label :categoty %><br />
  <%= f.select :category, options_for_select([
      ['Top'],['Bottom'],['Jacket'],['Shoes'],['Accessory']
    ]) , {} %>
  </div>

    <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>

  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>

  <div class="actions">
    <%= f.file_field :datafile %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>





<% end %>

app/views/clothings/edit.html.erb
<h1>Editing Clothing</h1>

<%= render 'form' %>

<%= link_to 'Show', @clothing %> |
<%= link_to 'Back', clothings_path %>

app/views/clothings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing clothings</h1>

<table>
  <thead>
    <tr>
      <th>Piece</th>
      <th>Category</th>
      <th>Brand</th>
      <th>Color</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clothings.each do |clothing| %>
      <tr>
        <td><%= clothing.description %></td>
        <td><%= clothing.category %></td>
        <td><%= clothing.brand %></td>
        <td><%= clothing.color %></td>
        <td><%= clothing.datafile %></td>
        <td><%= link_to 'Edit', edit_clothing_path(clothing) %></td>
        <td><%= link_to 'Destroy', clothing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Clothing', new_clothing_path %>

app/views/clothings/new.html.erb
<h1>New Clothing</h1>

<%= render 'form' %>

<%= link_to 'Back', clothings_path %>

app/views/clothings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @clothing.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @clothing.category %>
</p>

<p>
  <strong>BRand:</strong>
  <%= @clothing.brand %>
</p>

<p>
  <strong>Color:</strong>
  <%= @clothing.color %>
</p>

<p>
  <strong>Images:</strong>
  <%= @clothing.datafile %>
</p>

<%= link_to 'Edit', edit_clothing_path(@clothing) %> |
<%= link_to 'Back', clothings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MongoPeople</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/outfits/_form.html.erb
<%= form_for(@outfit) do |f| %>
  <% if @outfit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@outfit.errors.count, "error") %> prohibited this outfit from being saved:</h2>

      <ul>
      <% @outfit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event %><br>
    <%= f.text_field :event %>
  </div>
  <div class="field">
    <%= f.label :worn_on %><br>
    <%= f.date_select :worn_on %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>

  <div class="field">
  <%= f.label :tops %><br />
  <%= f.select(:clothing_ids, Clothing.where(category: "Top").collect {|a| [a.brand + " - " + a.description] }, {}, :multiple => true) %>
  </div>

    <div class="field">
  <%= f.label :bottoms %><br />
  <%= f.select(:clothing_ids, Clothing.where(category: "Bottom").collect {|a| [a.brand + " - " + a.description] }, {}, :multiple => true) %>
  </div>

    <div class="field">
  <%= f.label :jackets %><br />
  <%= f.select(:clothing_ids, Clothing.where(category: "Jacket").collect {|a| [a.brand + " - " + a.description] }, {}, :multiple => true) %>
  </div>

  <div class="field">
  <%= f.label :shoes %><br />
  <%= f.select(:clothing_ids, Clothing.where(category: "Shoes").collect {|a| [a.brand + " - " + a.description] }, {}, :multiple => true) %>
  </div>

  <div class="field">
  <%= f.label :accessories %><br />
  <%= f.select(:clothing_ids, Clothing.where(category: "Accessory").collect {|a| [a.brand + " - " + a.description] }, {}, :multiple => true) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/outfits/edit.html.erb
<h1>Editing outfit</h1>

<%= render 'form' %>

<%= link_to 'Show', @outfit %> |
<%= link_to 'Back', outfits_path %>

app/views/outfits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing outfits</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Notes</th>
      <th>Worn On</th>
      <th>Clothing</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @outfits.each do |outfit| %>
      <tr>
        <td><%= outfit.event %></td>
        <td><%= outfit.notes %></td>
        <td><%= outfit.worn_on %></td>
       <td><%= outfit.clothing_ids %></td>

        <td><%= link_to 'Show', outfit %></td>
        <td><%= link_to 'Edit', edit_outfit_path(outfit) %></td>
        <td><%= link_to 'Destroy', outfit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New outfit', new_outfit_path %>

app/views/outfits/new.html.erb
<h1>New Outfit</h1>

<%= render 'form' %>

<%= link_to 'Back', outfits_path %>

app/views/outfits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @outfit.event %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @outfit.notes %>
</p>

<p>
  <strong>Worn:</strong>
  <%= @outfit.worn_on %>
</p>

<p>
  <strong>Clothing:</strong>
  <%= @outfit.clothing_ids %>
</p>

<%= link_to 'Edit', edit_outfit_path(@outfit) %> |
<%= link_to 'Back', outfits_path %>